<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Nova.Pts\Nova.Pts.csproj" />
    <ProjectReference Include="..\..\third_party/dotnet-wpf/src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj">
      <ReferenceOutputAssembly>true</ReferenceOutputAssembly>
    </ProjectReference>
    <Reference Include="PresentationFramework">
      <HintPath>..\..\third_party\dotnet-wpf\artifacts\bin\PresentationFramework\Debug\$(TargetFramework)\PresentationFramework.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="PresentationCore">
      <HintPath>..\..\third_party\dotnet-wpf\artifacts\bin\PresentationCore\Debug\$(TargetFramework)\PresentationCore.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="WindowsBase">
      <HintPath>..\..\third_party\dotnet-wpf\artifacts\bin\WindowsBase\Debug\$(TargetFramework)\WindowsBase.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Xaml">
      <HintPath>..\..\third_party\dotnet-wpf\artifacts\bin\System.Xaml\Debug\$(TargetFramework)\System.Xaml.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
